# Generated by Django 4.2.5 on 2023-10-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publicada',
            field=models.CharField(choices=[('S', 'Publicada'), ('N', 'Não Publicada')], default='N', max_length=1),
        ),
    ]
